spring:
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: taofei
    password: taofei
    driver-class-name: com.mysql.jdbc.Driver
logging:
  level:
    com:
      example:
       mapper: debug
